# Generated by Django 4.1.4 on 2022-12-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('psevdonim', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
    ]
